### PR TITLE
add github link

### PR DESCRIPTION
**Pull request by skeeey**
Signed-off-by: Wei Liu <liuweixa@redhat.com>

### CODE REVIEW

**Comment by skeeey** [comment]
scree shot

截屏2021-11-02 下午4 35 15
截屏2021-11-02 下午4 35 47

**Comment by qiujian16** [comment]
should we put it on the top of getting started?

**Comment by qiujian16** [comment]
FYI @luckyfengyong

**Comment by skeeey** [comment]
This is the effect if we put the link on the top of the button

截屏2021-11-03 下午1 39 07


Do you think which is better? @qiujian16 @luckyfengyong

**Pull request merged**
