### PR TITLE
:bug: Fix broken links for addon developer guides

### PR DESCRIPTION
**Pull request by zhujian7**

### CODE REVIEW

**Review by mikeshng — COMMENTED** [review]
@zhujian7 is it on purpose that we are referring a commit and not the proper main branch url? ie: https://github.com/open-cluster-management-io/addon-framework/tree/main/cmd/example/busybox

**Comment by zhujian7** [comment]
> is it on purpose that we are referring a commit and not the proper main branch URL?

Hi @mikeshng , I am not quite sure which is better, just think that a commit is never broken. I can change it to the main branch if you suggest.

**Comment by dhaiducek** [comment]
> > is it on purpose that we are referring a commit and not the proper main branch URL?
> 
> Hi @mikeshng , I am not quite sure which is better, just think that a commit is never broken. I can change it to the main branch if you suggest.

As long as the example stays relevant and doesn't get updated, I think using a commit is fine. Otherwise, we'll have to remember to update the commit (and path since it's now `cmd/examples/busybox`) if the example changes. I could see it either way.

**Pull request merged**
