### PR TITLE
Add rollout strategy and update mwrSet

### PR DESCRIPTION
**Pull request by serngawy**

### CODE REVIEW

**Comment by haoqing0110** [comment]
LGTM. I will add more addon + rollout API examples in addon page.

**Comment by aii-nozomu-oki** [comment]
This is exactly what I wanted to know and I appreciate the attempt to document it.
By the way, what does "the successful state" mean?
Is it `AppliedManifestComplete: true`, `ResourceAvailable: true`, or something else?

**Comment by aii-nozomu-oki** [comment]
After examining the code, it seems to be determined from `ResourcesAvailable: true` in `status.conditions`. That true/false seems to use all of the `resourceStatus` fields.
I think it would be good to mention that in the documentation.
https://github.com/open-cluster-management-io/ocm/blob/29ffff020fafa88b8fbc898711313bc3eabeb6ef/pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_deploy_reconcile.go#L198
https://github.com/open-cluster-management-io/ocm/blob/29ffff020fafa88b8fbc898711313bc3eabeb6ef/pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go#L196
https://github.com/open-cluster-management-io/ocm/blob/29ffff020fafa88b8fbc898711313bc3eabeb6ef/pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go#L133C107-L133C121

It might be a good idea to briefly mention that in the documentation.

**Comment by serngawy** [comment]
> This is exactly what I wanted to know and I appreciate the attempt to document it. By the way, what does "the successful state" mean? Is it `AppliedManifestComplete: true`, `ResourceAvailable: true`, or something else?

mentioned the "the successful state" in placement as the successful state definition is different from one API to another; like for manifestwork successful mean resource is available, for other APIs is something else.

**Comment by serngawy** [comment]
> After examining the code, it seems to be determined from `ResourcesAvailable: true` in `status.conditions`. That true/false seems to use all of the `resourceStatus` fields. https://github.com/open-cluster-management-io/ocm/blob/29ffff020fafa88b8fbc898711313bc3eabeb6ef/pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_deploy_reconcile.go#L198 https://github.com/open-cluster-management-io/ocm/blob/29ffff020fafa88b8fbc898711313bc3eabeb6ef/pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go#L196 https://github.com/open-cluster-management-io/ocm/blob/29ffff020fafa88b8fbc898711313bc3eabeb6ef/pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go#L133C107-L133C121
> 
> It might be a good idea to briefly mention that in the documentation.

okay will add more info for that in the manifestWorkReplicaSet

**Pull request merged**
