### PR TITLE
re-enable applifecycle steps

### PR DESCRIPTION
**Pull request by mikeshng**
Signed-off-by: Mike Ng <ming@redhat.com>

### CODE REVIEW

**Review by qiujian16 — COMMENTED** [review]
@mikeshng do we have code ready?

**Comment by mikeshng** [comment]
> @mikeshng do we have code ready?

https://github.com/open-cluster-management-io/multicloud-operators-subscription

The described website instructions should be working already. There are still some work needed to be done on the repo for github actions, enhance readme and remove some more vendor specific references. I should be able to get those done by today. Just want the website have the website updated first because of timezone differences. I am ok if you think we should hold this. Thanks.

**Comment by qiujian16** [comment]
ok, @xuezhaojun would you like to take a look at this also? We might need some verification test on https://github.com/open-cluster-management-io/multicloud-operators-subscription also.

**Pull request merged**
