### PR TITLE
Small typo: January misspelled

### PR DESCRIPTION
**Pull request by mdelder**

### CODE REVIEW

**Comment by mikeshng** [comment]
Thank you for the fix @mdelder 
This is what I use to sign off on older commits:
```
git reset --soft HEAD~2
git commit -s -m "_commit_message_here_"
git push origin _branch_name_here_ -f
```
This should merge both commits into one and sign off on it.

**Comment by qiujian16** [comment]
@mdelder thanks. it needs to signoff. `git commit --amend -s`

**Comment by mikeshng** [comment]
This has been fixed in a separate PR. Thanks again for making us aware of this mistake Michael.

**Pull request closed without merging**
