### PR TITLE
Change cname

### PR DESCRIPTION
**Pull request by qiujian16**
Signed-off-by: Jian Qiu <jqiu@redhat.com>

### CODE REVIEW

**Comment by qiujian16** [comment]
/assign @mikeshng 
/hold

We need to merge it when we switch the open-clusterr-management.io

**Review by mikeshng — APPROVED** [review]
/lgtm

**Comment by mikeshng** [comment]
I think this is ready to go after @gurnben 's changes. 

Or maybe it's not needed anymore since everything seems to be working?

**Comment by gurnben** [comment]
In order to use the apex domain (open-cluster-management.io) as the domain for this GitHub pages - I had to use an alias record - so the CNAME isn't expressly necessary (to my knowledge)

**Pull request closed without merging**
