### PR TITLE
add a user scenario for deploying kubernetes resources

### PR DESCRIPTION
**Pull request by zhujian7**
Signed-off-by: zhujian <jiazhu@redhat.com>
Fixes: https://github.com/open-cluster-management-io/community/issues/83

- add a user scenario for deploying workloads
- move roadmap from concept to community
- put the community after the scenario

image

### CODE REVIEW

**Comment by zhujian7** [comment]
cc @elgnay

**Comment by qiujian16** [comment]
thanks, it looks good, would you squash the commit?

/approve

**Comment by zhujian7** [comment]
> would you squash the commit?

@qiujian16  I merged the commits to one, PTAL

**Pull request merged**
