### PR TITLE
add supporters section

### PR DESCRIPTION
**Pull request by skeeey**
Signed-off-by: Wei Liu <liuweixa@redhat.com>

### CODE REVIEW

**Comment by skeeey** [comment]
screen shot
截屏2021-11-04 上午10 21 18

截屏2021-11-04 上午10 21 40

**Comment by jberkus** [comment]
We need sign-offs on this PR from the owners of the logos.

**Comment by skeeey** [comment]
/hold

waiting sign-off

**Comment by luckyfengyong** [comment]
Ant Group could be added as well

**Comment by mikeshng** [comment]
Can IBM be added as well?

**Comment by skeeey** [comment]
add ant group and IBM logo, and waiting for further confirmation

截屏2021-11-08 下午2 41 16

**Comment by dixudx** [comment]
/lgtm

Signed-off-by: Di Xu <stephendixu@tencent.com>

**Comment by luckyfengyong** [comment]
/lgtm 

for Alibaba Cloud and Ant Group

**Comment by mikeshng** [comment]
@juliana-hsu could you please sign off on behalf of RH and IBM? Thanks.

**Comment by juliana-hsu** [comment]
Mike, I sign off for RH.  Is there someone that regularly participates from IBM that we can ask.

**Comment by qiujian16** [comment]
@skeeey would you rebase this pr, and we need to sort the logo by alphabetic according to CNCF policy.

**Comment by skeeey** [comment]
> @skeeey would you rebase this pr, and we need to sort the logo by alphabetic according to CNCF policy.

done

**Comment by skeeey** [comment]
I removed the IBM logo currently, I think we can merge this PR now, and I will use another pr to add the IBM logo after the process is finished

/cc @qiujian16 @mikeshng @juliana-hsu

**Pull request merged**
