### PR TITLE
update addon rollout api

### PR DESCRIPTION
**Pull request by haoqing0110**

### CODE REVIEW

**Comment by haoqing0110** [comment]
Hold this PR, will add more content for RolloutConfig field.

**Comment by haoqing0110** [comment]
After testing, the addon needs extra code changes to support MinSuccessTime, ProgressDeadline and MaxFailures
https://github.com/open-cluster-management-io/ocm/issues/332. So can merge this PR first, this PR only update some existing fileds examples.

**Comment by mikeshng** [comment]
CC @dhaiducek @mprahl who are also familiar with rollouts

**Review by serngawy — APPROVED** [review]

**Pull request merged**
