### PR TITLE
update placement concept

### PR DESCRIPTION
**Pull request by zhiweiyin318**
Signed-off-by: Zhiwei Yin <zyin@redhat.com>

### CODE REVIEW

**Comment by zhiweiyin318** [comment]
@haoqing0110 the Prioritizers part is not easy to understand, so I think more examples/scenarios could help user learn how to configure Prioritizers in placement.

**Comment by haoqing0110** [comment]
@zhiweiyin318 yes, thanks for the suggestion, the prioritizers have complex explanation now and not easy to understand. Let me log an issue to polish that part.

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
