### PR TITLE
Add `hub-addon` docs for policy framework

### PR DESCRIPTION
**Pull request by dhaiducek**
- Updates app to use `hub-addon` command:
  - https://github.com/open-cluster-management-io/clusteradm/pull/175
- Adds policy-framework `clusteradm` command:
  - https://github.com/open-cluster-management-io/clusteradm/pull/170
- Fixes some broken links

### CODE REVIEW

**Comment by dhaiducek** [comment]
/unhold

This is ready for review since `clusteradm` was released with the changes.

**Review by mikeshng — APPROVED** [review]
/lgtm

/approve

thank you for updating the app section as well!

**Pull request merged**
